apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_PRODUCT_SERVICE_URL
          value: "http://product-details:5000"
        - name: REACT_APP_DEALER_SERVICE_URL
          value: "http://dealer-pricing:3001"
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"